spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/energy_20231120306?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 439677
logging:
  level:
    com:
      example:
        elm_m:
          Mapper: debug
          Service: info
          Controller: info
springdoc:
  swagger-ui:
    persist-authorization: true
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.energy.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
energy:
  jwt:
    admin-secret-key: energy-jwt-secret-key-1234567890123456
    admin-ttl: 7200000
    admin-token-name: token

    user-ttl: 7200000
    user-token-name: authorization
    user-secret-key: energy-jwt-secret-key-1234567890123456